### ISSUE TITLE
Is the AdvancedCVAck version something to be pulled into master?

### ISSUE THREAD

**Issue by FrightRisk** [mrrwa/NmraDcc#40]
Hello. What is the difference between the two branches? Can you tell me how you are doing the ACK? What function is creating a current draw or is it only for Railcom where some piece of hardware does this? A standard Arduino had no ability to generate a 60mA pulse that I know of so for a decoder not attached to other hardware, have you thought of a way to send an ACK?

**Comment by kiwi64ajs** [comment]
Yes, this was merged on 9-Aug-2020
