### ISSUE TITLE
Compatibility with LGT8F328P

### ISSUE THREAD

**Issue by kamilbystryk** [mrrwa/NmraDcc#66]
Is the library compatible/works correctly with chinese clone of AtMega - LGT8F328P?

**Comment by devel-bobm** [comment]
If the board is truely a clone, then it should be compabible.

**Comment by kiwi64ajs** [comment]
Hmmm… I didn’t know about these chips or boards.I’ve just had a quick Google for them and from what I read I would expect it to work.Have you been able to try it yet?I’d have to order some to try it. RegardsAlex ShepherdOn 20/01/2023, at 2:32 AM, Bob Milhaupt ***@***.***> wrote:﻿
If the board is truely a clone, then it should be compabible.

**Comment by kamilbystryk** [comment]
Currently I cant check in practise - i'm waiting for sample and I will try it. 
Chinese processor isn't true clone, have some difference to oryginal Atmega (including another SDK/HAL).

**Comment by devel-bobm** [comment]
> Chinese processor isn't true clone, have some difference to oryginal Atmega

So it will depend entirely upon how well the chinese crap happens to mimic the ATMEL design.  I'd suggest that this "issue" belongs in the MRRWA mailing list, not in the Git repository!

**Comment by kamilbystryk** [comment]
Now I can confirm - library on LGT8F328P works correctly.

**Comment by kiwi64ajs** [comment]
Excellent, good to know.

I ordered a few from eBay, but they haven’t arrived yet so I’ve not been able to try.

Alex

**Comment by kiwi64ajs** [comment]
Confirmed that it works on this chip
