### ISSUE TITLE
Question - Railcom support planned ?

### ISSUE THREAD

**Issue by chatelao** [mrrwa/NmraDcc#82]
I have a little question:

- Is there any RailCom support planned for the library?

**Comment by kiwi64ajs** [comment]
No, not by me, at least... ;) 
It requires specialised electronic circuitry to facilitate the data transfer, which is beyond my capability.
Perhaps some brave and clever person will find a way to add it.

**Comment by chatelao** [comment]
As soon as I will have the hardware issue solved, I will come back :-)

**Comment by kiwi64ajs** [comment]
Wow, sounds exciting!!! ;)

**Comment by chatelao** [comment]
Sneak preview of a OSHW 8x accessory decoder "coming soon" (aka 1 or 2 HW debug rounds left ahead).
=> I will be powered by any Seeed XIAO / Adafruit QT board you like - My favorit is still the XIAO RP2040

![image](https://github.com/user-attachments/assets/cd3d8abe-bf64-4dd1-a1b5-f3c0c79dc322)
