### ISSUE TITLE
compile fail

### ISSUE THREAD

**Issue by egstubbe** [mrrwa/NmraDcc#85]
I am running into a compile problem.
I am trying to compile the motor decoder example file.
I am on a Mac with the latest version of Arduino IDE  set for ATTiny85,16 MHz internal clock,ATTiny85 processor selected.
Get the error message "Unsupported CPU" Add another config section for your CPU exit status1.
Error is in line #55 of the sketch.
I compiled another DCC sketch using DCC_Decoder.h set the same settings as above and it compiles ok.
It looks like the IDE is setup for the ATTiny chips unless I am missing something.
This is a first time post if I did it wrong let me know.
My email is egstubbe@aol.com.
Thanks.

**Comment by kiwi64ajs** [comment]
Hi egstubbe,

Hmmm… there must be something else going on or a difference between our Arduino Envontonments as I can select the ATtiny85 variant CPU from the ATTinyCore and compile the NmraDccMultiFunctionMotorDecoder without error. See the screenshot below. 

The version of my Arduino IDE is 2.3.3, the ATTinyCore version is 1.5.2, and the NmraDcc version is 2.0.17

I’m also on a MacBook Air running macOS 14.7.1

How does that compare to your system?

Alex


￼

**Comment by kiwi64ajs** [comment]
This issue was caused by the wrong Arduino core ATTiny instead of ATTinyCore. Switching to ATTinyCore made the problem go away.
