### ISSUE TITLE
Help request

### ISSUE THREAD

**Issue by Petej42** [mrrwa/NmraDcc#87]
Is anyone available to take a look at some arduino code using the  nmradcc library.
I am trying to put something together that allows me to control 17 servo controlled turnouts. The turnout attributes are stored as objects in an array, however when I call dcc.process, the last element in the turnout array gets corrupted and I cannot determine why, even with the code stripped back yto a minimum

**Comment by Petej42** [comment]
[TurnoutControl_bare.ino.txt](https://github.com/user-attachments/files/17882642/TurnoutControl_bare.ino.txt)

**Comment by kiwi64ajs** [comment]
I think your Turnout Array is one element short. Try changing this line:

	Turnout to[noTurnouts-1];

to:

	Turnout to[noTurnouts];

HTH

Alex Shepherd

**Comment by mijnmodelbaan** [comment]
I think Alex is right and if not, what happens if you try 16 servos?

BR/Willem.

**Comment by Petej42** [comment]
You know, I was pondering over this for hours last night, of course the array size is wrong, the annoying thing is **I know this** and even changed it to Turnout to[noTurnouts]; at one point and thought "oh that works, wonder why", this is what happens when you try and do this type of thing at this time of night.

Many thanks both, and sincere apologies for wasting your time on such a rudimentary mistake.
