### ISSUE TITLE
Execution order wrong on Dec_Dir_and_Fade, decoder address is never set

### ISSUE THREAD

**Issue by adamszendrey** [mrrwa/NmraDcc#88]
Dec_Dir_and_Fade needs a minor change, because as is, it doesn't work correctly:
`Dcc.Init()`, should happen before ` #if defined(DECODER_LOADED)`, otherwise the address is not being set to the predefined value.

**Comment by kiwi64ajs** [comment]
Thanks for that, I've committed the change to the repository, which will go out in the next release
